version: "3.3"

services:

  paperyard:
    depends_on:
      - db
    restart: always
    build: .
    container_name: paperyard
    tty: true
    ports:
     - "80:80"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: paperyard_db
